language: java
jdk: openjdk11
script:
- mvn clean install
- mvn package
- git status
git:
  depth: 1
before_install:
- openssl aes-256-cbc -K $encrypted_0984cd22fdc0_key -iv $encrypted_0984cd22fdc0_iv
  -in .travis_deploy_key.enc -out .travis_deploy_key -d
