language: java
jdk: openjdk11

before_install:
  - openssl aes-256-cbc -K $encrypted_0984cd22fdc0_key -iv $encrypted_0984cd22fdc0_iv
    -in .travis_deploy_key.enc -out .travis_deploy_key -d

script:
  - ls -a
  - git status

git:
  depth: 1