micronaut:
  application:
    name: winston

bot:
  token: ${WINSTON_TOKEN}
  guild:
    id: 621621615930638336
  config:
    registerCommands: false
    registerCommandsGlobally: false
    registerCommandsForGuild: true

spotify:
  client:
    id: ${SPOTIFY_CLIENT_ID}
    secret: ${SPOTIFY_CLIENT_SECRET}

youtubeLogo: "https://www.vexels.com/media/users/3/137425/isolated/thumb/f2ea1ded4d037633f687ee389a571086-youtube-icon-logo-by-vexels.png"
spotifyLogo: "https://developer.spotify.com/assets/branding-guidelines/icon4@2x.png"
winstonWednesday: "classpath:winstonWednesday.mp4"
